### ISSUE TITLE
Video not availaible !

### ISSUE THREAD

**Issue by lillois59** [arnav-kr/tor-tutorial#1]
Hi,

good work bro but your video are not longer availeble sorry can you post it again thanks

http://nbrmr5m4gekl2lkof4kkarjfwpuaa745yfgmrnpn7bfjsoclm7g2lxad.onion/

**Comment by arnav-kr** [comment]
Hey seems like you got a bit confused here.
that URL is not for the video tutorial.

It is the live working result that you will get after you host your own site from this tutorial
Also as mentioned in the tutorial `.onion`  domains are special domains that can only be viewed in the tor browser.
So consider installing the [Tor Browser](https://www.torproject.org/download/) and viewing the URL in that.
Also, I have done some updates to the tutorial regarding the security of your website, so make sure to check that too

also, I have updated the URL
and http://yfjcqmwksq5trzghb3ekiam6krszdb2wq7bmirmjxvbifxudl4mu4ead.onion/ is the new URL.

feel free to ask any other issue
for now closing this issue

**Comment by lillois59** [comment]
Hi, I'm not confused I know it's onion standard link and sure I've already Tor installed into my MBP high Sierra! Can you please help me to configure onion link using OSX and Nginx please thanks a lot

**Comment by arnav-kr** [comment]
Try this https://dev.to/arthtyagi/how-to-setup-a-tor-hidden-service-5gpn

**Comment by lillois59** [comment]
Worked bro thanks again!

**Comment by arnav-kr** [comment]
have a Bug Free day (though not possible lol)
